import sys
import datetime
from lxml import etree
from sqlalchemy import Column, Integer, String, Sequence, Text, DateTime

from fetcher import Fetcher
from client import app
#from database import Base, engine, session


#class Article(Base):
class Article():
    """
    Retrieves the article from the website.
    TODO: Expose methods for storing article in the database.
    """
    #__tablename__ = "articles"

    # Create instance with Article(slug) => Article("newton")
    # this class will check for the article in the db and render it
    # if it exists, otherwise will fetch it, store the metadata in
    # the db, and then render the article

    """
    id       = Column(Integer, Sequence("post_id_sequence"), primary_key=True)
    title    = Column(String(1024))
    content  = Column(Text)
    datetime = Column(DateTime, default=datetime.datetime.now)
    """

    def __init__(self, url):
        self.url = url

    def wordcount(self, article):
        """
        Given article content, calculate the number of words.
        """



class SEP(Article):
    """
    Parses the SEP article content.
    """
    base_url = "http://plato.stanford.edu/entries/"
    xpaths   = {
        "title"     : '//*[@id="aueditable"]/h1/text()',
        "pubdate"   : '//*[@id="pubinfo"]/*/text()',
        "lede"      : '//*[@id="preamble"]/p',
        "toc"       : '//*[@id="toc"]/ul/li/a',
        "text"      : '//*[@id="main-text"]',
        "biblio"    : '//*[@id="bibliography"]',
        "resources" : '//*[@id="other-internet-resources"]',
        "related"   : '//*[@id="related-entries"]',
        "thanks"    : '//*[@id="acknowledgments"]',
    }


    def __init__(self, slug):
        # Setup
        self.url = self.base_url + slug
        app.logger.info("Creating SEP instance: " + self.url)

        # Generate object content
        dl = Fetcher(self.url)
        self.response = dl.fetch(self.url)
        self.tree     = etree.HTML(self.response.text)
        self.content  = self.parse()
        self.content['url'] = self.url
        app.logger.info(slug + " instance created.")


    def parse(self):
        """
        Parses the HTML tree generated by self.get_tree() into a dictionary of
        the form {<description> : <content>}.
        """
        d = {}
        # TODO: convert to list comprehension?
        for k in self.xpaths:
            y = []
            x = self.tree.xpath(self.xpaths[k])
            for i in x:
                if type(i) == etree._Element:
                   y.append(etree.tostring(i,encoding="Unicode"))
                else:
                    y.append(i)
            d[k] = y

        return d



#Base.metadata.create_all(engine)
